version: '3'

services:
  bot:
    build: .
    environment:
      - MATTERMOST_URL=http://localhost
      - MATTERMOST_TOKEN=1g47748hbfrz3b8qeapbfadgfe
      - TARANTOOL_ADDR=tarantool:3301
    depends_on:
      - tarantool

  tarantool:
    image: tarantool/tarantool:latest
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool:/var/lib/tarantool
    environment:
      - TARANTOOL_USER_NAME=admin
      - TARANTOOL_USER_PASSWORD=password